import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { useRouter } from "next/router";
import NewPostForm from "../../components/NewPostForm";

import { api } from "../../utils/api";

const CategoryPage: NextPage = () => {
  const router = useRouter();
  const session = useSession();

  const id = router.query.id;

  const {data: posts, isLoading} = api.post.getPosts.useQuery({categoryId: id as string})

  if(isLoading) return <div>Loading...</div>

  let msg;

  let postsList;

  if(posts?.length === 0){
    postsList = <div>No posts yet</div>
  }else{
    postsList = posts?.map((post) => {
      return (
        <div key={post.id}>
          <Link href={`/post/${post.id}`}>
            {post.title}
          </Link>
        </div>
      );
    });
  }

  if (session.data?.user) {
    msg = (
      <div>
        <h1>Logged in as {session.data.user.name}</h1>
        <button
          onClick={() => {
            signOut().catch(console.log);
          }}
        >
          Sign Out
        </button>
        <NewPostForm />
      </div>
    );
  } else {
    msg = (
      <div>
        <h1>Not logged in</h1>
        <button
          onClick={() => {
            signIn("discord").catch(console.log);
          }}
        >
          Sign In
        </button>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>T3 Forum</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {msg}
      {postsList}
    </>
  );
};

export default CategoryPage;